// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace PocketJudge.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class Data
    {
        /// <summary>
        /// Initializes a new instance of the Data class.
        /// </summary>
        public Data() { }

        /// <summary>
        /// Initializes a new instance of the Data class.
        /// </summary>
        public Data(int mark, string competence, string project)
        {
            Mark = mark;
            Competence = competence;
            Project = project;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "mark")]
        public int Mark { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "competence")]
        public string Competence { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "project")]
        public string Project { get; set; }

        /// <summary>
        /// Validate the object. Throws ValidationException if validation fails.
        /// </summary>
        public virtual void Validate()
        {
            if (Competence == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Competence");
            }
            if (Project == null)
            {
                throw new ValidationException(ValidationRules.CannotBeNull, "Project");
            }
        }
    }
}
