# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 10:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('max_mark', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Competence')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Judge')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1024, null=True)),
                ('contestants', models.ManyToManyField(to='app.Contestant')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
        migrations.AddField(
            model_name='contest',
            name='judges',
            field=models.ManyToManyField(to='app.Judge'),
        ),
        migrations.AddField(
            model_name='contest',
            name='parent_contest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Contest'),
        ),
        migrations.AddField(
            model_name='competence',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Contest'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set([('competence', 'project', 'judge')]),
        ),
    ]
