# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-05 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id_competence', models.AutoField(db_column='IdCompetence', primary_key=True, serialize=False)),
                ('max_score', models.IntegerField(db_column='MaxScore')),
            ],
            options={
                'db_table': 'Competence',
            },
        ),
        migrations.CreateModel(
            name='CompetenceType',
            fields=[
                ('id_competence_type', models.AutoField(db_column='IdCompetenceType', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'CompetenceType',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id_contest', models.AutoField(db_column='IdContest', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=1024, null=True)),
                ('datetime_begin', models.DateTimeField(db_column='DatetimeBegin')),
                ('datetime_end', models.DateTimeField(blank=True, db_column='DatetimeEnd', null=True)),
                ('max_count_contestant_on_project', models.IntegerField(blank=True, db_column='MaxCountContestantOnProject', null=True)),
                ('max_count_project_on_contestant', models.IntegerField(blank=True, db_column='MaxCountProjectOnContestant', null=True)),
                ('contestant_judge', models.BooleanField(db_column='ContestantJudge')),
            ],
            options={
                'db_table': 'Contest',
            },
        ),
        migrations.CreateModel(
            name='Contestant',
            fields=[
                ('id_contestant', models.AutoField(db_column='IdContestant', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Contestant',
            },
        ),
        migrations.CreateModel(
            name='Judge',
            fields=[
                ('id_judge', models.AutoField(db_column='IdJudge', primary_key=True, serialize=False)),
                ('datetime_session_end', models.DateTimeField(blank=True, db_column='DatetimeSessionEnd', null=True)),
                ('contest', models.ForeignKey(db_column='IdContest', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Contest')),
                ('user', models.ForeignKey(db_column='IdUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Judge',
            },
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id_mark', models.AutoField(db_column='IdMark', primary_key=True, serialize=False)),
                ('score', models.IntegerField(db_column='Score')),
                ('competence', models.ForeignKey(db_column='IdCompetence', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Competence')),
                ('judge', models.ForeignKey(db_column='IdJudge', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Judge')),
            ],
            options={
                'db_table': 'Mark',
            },
        ),
        migrations.CreateModel(
            name='MarkAvailabilityType',
            fields=[
                ('id_mark_availability_type', models.AutoField(db_column='IdMarkAvailabilityType', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
            ],
            options={
                'db_table': 'MarkAvailabilityType',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id_project', models.AutoField(db_column='IdProject', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=1024, null=True)),
                ('contest', models.ForeignKey(db_column='IdContest', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Contest')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.AddField(
            model_name='mark',
            name='project',
            field=models.ForeignKey(db_column='IdProject', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Project'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='project',
            field=models.ForeignKey(db_column='IdProject', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Project'),
        ),
        migrations.AddField(
            model_name='contestant',
            name='user',
            field=models.ForeignKey(db_column='IdUser', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contest',
            name='mark_availability_type',
            field=models.ForeignKey(db_column='IdMarkAvailabilityType', on_delete=django.db.models.deletion.DO_NOTHING, to='app.MarkAvailabilityType'),
        ),
        migrations.AddField(
            model_name='contest',
            name='parent_contest',
            field=models.ForeignKey(blank=True, db_column='IdParentContest', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Contest'),
        ),
        migrations.AddField(
            model_name='competence',
            name='competence_type',
            field=models.ForeignKey(db_column='IdCompetenceType', on_delete=django.db.models.deletion.DO_NOTHING, to='app.CompetenceType'),
        ),
        migrations.AddField(
            model_name='competence',
            name='contest',
            field=models.ForeignKey(db_column='IdContest', on_delete=django.db.models.deletion.DO_NOTHING, to='app.Contest'),
        ),
        migrations.AlterUniqueTogether(
            name='mark',
            unique_together=set([('competence', 'project', 'judge')]),
        ),
        migrations.AlterUniqueTogether(
            name='judge',
            unique_together=set([('contest', 'user')]),
        ),
        migrations.AlterUniqueTogether(
            name='contestant',
            unique_together=set([('user', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='competence',
            unique_together=set([('competence_type', 'contest')]),
        ),
    ]
