# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20161121_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contest',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.Contest'),
            preserve_default=False,
        ),
    ]
