# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_project_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
