# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161121_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competence',
            name='contest',
        ),
        migrations.AddField(
            model_name='contest',
            name='competences',
            field=models.ManyToManyField(to='app.Competence'),
        ),
    ]
