# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-14 11:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20161121_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='competences',
            field=models.ManyToManyField(blank=True, to='app.Competence'),
        ),
        migrations.AlterField(
            model_name='project',
            name='contest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='app.Contest'),
        ),
    ]
